version: "3"

services:
  unbound:
    #image: eugenmayer/unbound:1.17
    image: mvance/unbound:1.17.0
    volumes:
    - ./test/01_records.conf:/etc/unbound/conf.d/01_records.conf
    - ./test/02_forward.conf:/etc/unbound/conf.d/02_forward.conf
    ports:
    - 55:53
    - 55:53/udp