version: "3"

services:
  unbound:
    image: ghcr.io/eugenmayer/unbound:1.17
    volumes:
    - ./test/01_records.conf:/etc/unbound/conf.d/01_records.conf
    - ./test/02_forward.conf:/etc/unbound/conf.d/02_forward.conf
    ports:
    - 55:53
    - 55:53/udp
