version: "2"

services:
  unbound:
    image: eugenmayer/unbound:1.8
    volumes:
    - ./test/01_records.conf:/etc/unbound/conf.d/01_records.conf
    - ./test/02_forward.conf:/etc/unbound/conf.d/02_forward.conf
    ports:
    - 55:53
    - 55:53/udp